"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { motion } from "framer-motion";
import { GitBranch } from "lucide-react";

import { AiInput } from "@/components/ui/ai-input";
import { BackgroundPaperShaders } from "@/components/ui/background-paper-shaders";

type PredictResponse = {
  label: "Human" | "AI";
  confidence: number;
  probability_ai: number;
  probability_human: number;
  model_name: string;
  model_type: string;
};

export default function Page() {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [result, setResult] = useState<PredictResponse | null>(null);
  const [isLocalhost, setIsLocalhost] = useState(true);

  useEffect(() => {
    const host = window.location.hostname;
    setIsLocalhost(host === "localhost" || host === "127.0.0.1" || host === "::1" || host === "[::1]");
  }, []);

  async function runPrediction(text: string) {
    if (!isLocalhost) {
      setError("Classification is only enabled locally. Run the server on localhost to try it.");
      return;
    }

    setError("");
    setResult(null);
    setLoading(true);

    try {
      const res = await fetch("/api/predict", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ text }),
      });

      const data = await res.json();
      if (!res.ok) {
        throw new Error(data?.error || "Prediction failed");
      }

      setResult(data as PredictResponse);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Unexpected error");
    } finally {
      setLoading(false);
    }
  }

  return (
    <main className="mx-auto min-h-dvh w-full max-w-6xl px-4 pb-12 pt-6 sm:px-6">
      <motion.section
        initial={{ opacity: 0, y: 10 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.35 }}
        className="hero-row"
      >
        <div className="hero-shell">
          <BackgroundPaperShaders className="hero-shader [mask-image:radial-gradient(ellipse_at_center,black_42%,transparent_85%)]" />
          <div className="hero-content text-center">
            <p className="kicker">CS 561 Final Project</p>
            <h1 className="hero-title mt-3">
              <span className="ai-word">AI</span> vs Human Writing Detection
            </h1>
            <p className="lede mx-auto mt-5 max-w-2xl">Find if your text is AI or not</p>
            <div className="mt-7 flex flex-wrap justify-center gap-3">
              <Link href="/findings" className="nav-link">
                View Findings
              </Link>
              <a
                href="https://github.com/darielgu/561-final"
                target="_blank"
                rel="noreferrer"
                className="nav-link inline-flex items-center gap-2"
              >
                <GitBranch className="h-4 w-4" />
                View GitHub
              </a>
            </div>
          </div>
        </div>
      </motion.section>

      <motion.section
        initial={{ opacity: 0, y: 8 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.35, delay: 0.05 }}
        className="panel p-5 sm:p-6"
      >
        <h2 className="section-title mb-4">Project Context</h2>
        <div className="grid gap-5 text-sm leading-relaxed text-white/85 md:grid-cols-2">
          <div>
            <h3 className="meta">Background + Problem</h3>
            <p className="mt-2">
              NLP text classification is used here to identify whether text was written by a human or generated by AI
              models, supporting concerns around education, academic integrity, and content authenticity.
            </p>
          </div>
          <div>
            <h3 className="meta">Dataset</h3>
            <p className="mt-2">
              Kaggle ai-and-human-text-dataset with 6,069 samples. Labels:
              <span className="font-mono"> 0 = Human</span> and <span className="font-mono">1 = AI</span>.
            </p>
          </div>
          <div>
            <h3 className="meta">Methods</h3>
            <p className="mt-2">
              Text is lowercased, tokenized, and cleaned with stop-word removal. TF-IDF transforms text to features,
              then models are compared across TF-IDF baseline and BERT.
            </p>
          </div>
          <div>
            <h3 className="meta">Evaluation</h3>
            <p className="mt-2">
              We evaluate with accuracy, precision, recall, and F1 to compare baseline ML performance against advanced
              model approaches.
            </p>
          </div>
        </div>
      </motion.section>

      <motion.section
        initial={{ opacity: 0, y: 8 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.35, delay: 0.1 }}
        className="panel mt-5 p-5 sm:p-6"
      >
        <div className="mb-4 flex flex-wrap items-center justify-between gap-3">
          <h2 className="section-title">Run Classifier</h2>
          <span className="mono-tag">TF-IDF + Logistic Regression</span>
        </div>
        {!isLocalhost ? (
          <div className="mb-3 border border-white/30 bg-white/10 px-3 py-2 text-sm text-white/90">
            Classification is only enabled locally. Run this app on <span className="font-mono">localhost</span> to
            try detection.
          </div>
        ) : null}
        <AiInput onSubmitText={runPrediction} isLoading={loading} isDisabled={!isLocalhost} />
        {error ? <div className="notice mt-3">{error}</div> : null}
        {result ? (
          <motion.div initial={{ opacity: 0, y: 6 }} animate={{ opacity: 1, y: 0 }} className="result-card mt-4 p-3">
            <div className="mb-3 flex items-center justify-between">
              <h3 className="section-title">Prediction</h3>
              <span className="mono-tag">{result.label}</span>
            </div>
            <div className="grid gap-2 text-sm sm:grid-cols-[170px_1fr]">
              <strong>Confidence</strong>
              <span className="font-mono">{(result.confidence * 100).toFixed(2)}%</span>
              <strong>P(AI)</strong>
              <span className="font-mono">{result.probability_ai.toFixed(4)}</span>
              <strong>P(Human)</strong>
              <span className="font-mono">{result.probability_human.toFixed(4)}</span>
              <strong>Model</strong>
              <span className="font-mono">{result.model_name}</span>
              <strong>Type</strong>
              <span className="font-mono">{result.model_type}</span>
            </div>
          </motion.div>
        ) : null}
      </motion.section>
    </main>
  );
}
